title: "Querido Programador"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 9
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  isaac:
    name: Isaac
    display_name: Isaac
    avatar: 'assets/images/sal.png'
    email: isaacdelosredi@gmail.com
    web: https://iesedobleac.github.io/
    twitter: https://twitter.com/iesedobleac
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
social:
  twitter: https://twitter.com/iesedobleac
  linkedin: https://www.linkedin.com/in/isaacdelosreyesdiaz/
  email: isaacdelosredi@gmail.com

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives