title: "Querido Programador"
tagline: "Blog que nace con la idea de compartir lo que voy aprendiendo día a día sobre programación."
email: isaacdelosredi@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Isaac
paginate: 9
locale: es_es
lang: es_es
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  isaac:
    name: Isaac
    display_name: Isaac
    avatar: 'assets/images/isaac.webp'
    email: isaacdelosredi@gmail.com
    web: https://queridoprogramador.com/
    twitter: https://twitter.com/iesedobleac
    description: "Autor de Querido Programador. Desarrollador sevillano centrado en programación móvil con ganas de aprender y sobretodo enseñar al resto lo que está aprediendo."

# Social
social:
  twitter: https://twitter.com/iesedobleac
  linkedin: https://www.linkedin.com/in/isaacdelosreyesdiaz/
  email: isaacdelosredi@gmail.com

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives